# PHP project
language: php

# which versions of PHP to build with
php:
- 7.0

# set global environment variables
env:
  global:
    # make PROJECTNAME from vendor/project
    # this strips everything before the last /
    - PROJECTNAME=${TRAVIS_REPO_SLUG##*/}

# make sure we have the latest version of composer
before_install:
- composer self-update

# install dependencies
install:
- composer install

# no phpunit tests (yet)
script: true

# no email notifications
notifications:
  email: false

# before deployment make the zipfile to upload
before_deploy:
 # execute release prepare script
 - sh ./vendor/coldtrick/releases/scripts/travis/before_deploy.sh

# deployment settings
deploy:
  provider: releases
  api_key:
    secure: Y44NMe9o+0G1k0AtTRvHGN5FbbDocpoW70QlTKmxsLGPTAA1RsNAAXPkpz4b+PztoZTTUywAi6WrszSo2F5eYTdpNzbxhE/bGGtH/WHNGOOSkhwHxLQwEHpjI+IVPQ6m6EcpuWFZ0nQJBcP2wST1E4iRVk8Q60dUPeYp1vaheus=
  # name of the zip to upload
  file: ${PROJECTNAME}_$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    # only when a tag is created in GitHub
    tags: true
    all_branches: true

after_deploy:
 # execute release after script
 - sh ./vendor/coldtrick/releases/scripts/travis/after_deploy.sh
